/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as ToolsNewRouteImport } from './routes/tools/new'
import { Route as ToolsMyToolsRouteImport } from './routes/tools/my-tools'
import { Route as ToolsIdRouteImport } from './routes/tools/$id'
import { Route as ToolsIdEditRouteImport } from './routes/tools/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsNewRoute = ToolsNewRouteImport.update({
  id: '/tools/new',
  path: '/tools/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMyToolsRoute = ToolsMyToolsRouteImport.update({
  id: '/tools/my-tools',
  path: '/tools/my-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIdRoute = ToolsIdRouteImport.update({
  id: '/tools/$id',
  path: '/tools/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIdEditRoute = ToolsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ToolsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools/$id': typeof ToolsIdRouteWithChildren
  '/tools/my-tools': typeof ToolsMyToolsRoute
  '/tools/new': typeof ToolsNewRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$id/edit': typeof ToolsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools/$id': typeof ToolsIdRouteWithChildren
  '/tools/my-tools': typeof ToolsMyToolsRoute
  '/tools/new': typeof ToolsNewRoute
  '/tools': typeof ToolsIndexRoute
  '/tools/$id/edit': typeof ToolsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/tools/$id': typeof ToolsIdRouteWithChildren
  '/tools/my-tools': typeof ToolsMyToolsRoute
  '/tools/new': typeof ToolsNewRoute
  '/tools/': typeof ToolsIndexRoute
  '/tools/$id/edit': typeof ToolsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/tools/$id'
    | '/tools/my-tools'
    | '/tools/new'
    | '/tools/'
    | '/tools/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/tools/$id'
    | '/tools/my-tools'
    | '/tools/new'
    | '/tools'
    | '/tools/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/tools/$id'
    | '/tools/my-tools'
    | '/tools/new'
    | '/tools/'
    | '/tools/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ToolsIdRoute: typeof ToolsIdRouteWithChildren
  ToolsMyToolsRoute: typeof ToolsMyToolsRoute
  ToolsNewRoute: typeof ToolsNewRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/new': {
      id: '/tools/new'
      path: '/tools/new'
      fullPath: '/tools/new'
      preLoaderRoute: typeof ToolsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/my-tools': {
      id: '/tools/my-tools'
      path: '/tools/my-tools'
      fullPath: '/tools/my-tools'
      preLoaderRoute: typeof ToolsMyToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$id': {
      id: '/tools/$id'
      path: '/tools/$id'
      fullPath: '/tools/$id'
      preLoaderRoute: typeof ToolsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$id/edit': {
      id: '/tools/$id/edit'
      path: '/edit'
      fullPath: '/tools/$id/edit'
      preLoaderRoute: typeof ToolsIdEditRouteImport
      parentRoute: typeof ToolsIdRoute
    }
  }
}

interface ToolsIdRouteChildren {
  ToolsIdEditRoute: typeof ToolsIdEditRoute
}

const ToolsIdRouteChildren: ToolsIdRouteChildren = {
  ToolsIdEditRoute: ToolsIdEditRoute,
}

const ToolsIdRouteWithChildren =
  ToolsIdRoute._addFileChildren(ToolsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ToolsIdRoute: ToolsIdRouteWithChildren,
  ToolsMyToolsRoute: ToolsMyToolsRoute,
  ToolsNewRoute: ToolsNewRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
